// <auto-generated />
using Ecommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "cat1.jpg",
                            Name = "Outdoor Plants"
                        },
                        new
                        {
                            Id = 2,
                            Image = "cat2.jpg",
                            Name = "Houseplants"
                        },
                        new
                        {
                            Id = 3,
                            Image = "cat3.jpg",
                            Name = "Succulents"
                        },
                        new
                        {
                            Id = 4,
                            Image = "cat4.jpg",
                            Name = "Desert Bloom"
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "This is Desert Bloom",
                            Image = "product1.jpg",
                            Name = "Desert Bloom",
                            Price = 60m,
                            Quantity = 10,
                            Rate = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "This is Golden Glow",
                            Image = "product2.jpg",
                            Name = "Golden Glow",
                            Price = 85m,
                            Quantity = 5,
                            Rate = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "This is Silver Mist",
                            Image = "product3.jpg",
                            Name = "Silver Mist",
                            Price = 100m,
                            Quantity = 20,
                            Rate = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "This is Zen Bamboo Grove",
                            Image = "product4.jpg",
                            Name = "Zen Bamboo Grove",
                            Price = 10.5m,
                            Quantity = 1,
                            Rate = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "This is Tropical Breeze",
                            Image = "product5.jpg",
                            Name = "Tropical Breeze",
                            Price = 200m,
                            Quantity = 8,
                            Rate = 0
                        });
                });

            modelBuilder.Entity("Ecommerce.Models.Product", b =>
                {
                    b.HasOne("Ecommerce.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
